PUT http://localhost:4004/api/device/update
Content-Type: application/json

{
  "deviceId": "D2",
  "action": true
}
###
POST http://localhost:4004/api/device/create
Content-Type: application/json
Accept: application/json

{
  "deviceId": "D1",
  "name": "Fan",
  "description": "Quạt"
}
###
POST http://localhost:4004/api/sensor/create
Content-Type: application/json
Accept: application/json

{
  "sensorId": "S1",
  "name": "Thanh-Sensor",
  "address": "localhost-THANH"
}

###
GET http://localhost:4004/api/device
